<?php

namespace Shift\Packages;

class Registry
{
    public static function laravelCorePackages(string $version): array
    {
        $constraints = [
            '8.0' => [
                "facade/ignition" => ['type' => 'require-dev', 'constraint' => "^2.3.6"],
                "fideloper/proxy" => ['type' => 'require', 'constraint' => "^4.2"],
                "fruitcake/laravel-cors" => ['type' => 'require', 'constraint' => "^2.0"],
                "fzaninotto/faker" => ['type' => 'require-dev', 'constraint' => "^1.9.1"],
                "guzzlehttp/guzzle" => ['type' => 'require', 'constraint' => "^7.0.1"],
                "laravel/tinker" => ['type' => 'require', 'constraint' => "^2.0"],
                "mockery/mockery" => ['type' => 'require-dev', 'constraint' => "^1.3.1"],
                "nunomaduro/collision" => ['type' => 'require-dev', 'constraint' => "^5.0"],
                "php" => ['type' => 'require', 'constraint' => "^7.3"],
                "phpunit/phpunit" => ['type' => 'require-dev', 'constraint' => "^9.3"],
            ],
            '7.0' => [
                'fideloper/proxy' => ['type' => 'require', 'constraint' => '^4.2'],
                'fruitcake/laravel-cors' => ['type' => 'require', 'constraint' => '^2.0'],
                'fzaninotto/faker' => ['type' => 'require-dev', 'constraint' => "^1.9.1"],
                'guzzlehttp/guzzle' => ['type' => 'require', 'constraint' => '^6.3'],
                'laravel/tinker' => ['type' => 'require', 'constraint' => '^2.0'],
                'mockery/mockery' => ['type' => 'require-dev', 'constraint' => '^1.3.1'],
                'nunomaduro/collision' => ['type' => 'require-dev', 'constraint' => '^4.1'],
                'php' => ['type' => 'require', 'constraint' => '^7.2.5'],
                'phpunit/phpunit' => ['type' => 'require-dev', 'constraint' => "^8.5"],
            ],
            '6.0' => [
                'facade/ignition' => ['type' => 'require-dev', 'constraint' => "^1.4"],
                'fideloper/proxy' => ['type' => 'require', 'constraint' => '^4.0'],
                'fzaninotto/faker' => ['type' => 'require-dev', 'constraint' => "^1.9.1"],
                'laravel/tinker' => ['type' => 'require', 'constraint' => '^2.0'],
                'mockery/mockery' => ['type' => 'require-dev', 'constraint' => '^1.0'],
                'nunomaduro/collision' => ['type' => 'require-dev', 'constraint' => '^3.0'],
                'php' => ['type' => 'require', 'constraint' => '^7.2'],
                'phpunit/phpunit' => ['type' => 'require-dev', 'constraint' => "^8.0"],
            ],
        ];

        return $constraints[$version] ?? [];
    }

    public static function laravelCommunityPackages(string $version): array
    {
        $constraints = [
            '8.0' => [
                // TODO:
            ],
            '7.0' => [
                'altek/accountant' => ['type' => 'require', 'constraint' => '^2.0'],
                'arcanedev/log-viewer' => ['type' => 'require', 'constraint' => '^7.0'],
                'barryvdh/laravel-ide-helper' => ['type' => 'require-dev', 'constraint' => '^2.6.7'],
                'beyondcode/laravel-websockets' => ['type' => 'require', 'constraint' => '^1.3'],
                'cmgmyr/laravel-messenger' => ['type' => 'require', 'constraint' => '^2.20'],
                'codedungeon/phpunit-result-printer' => ['type' => 'require-dev', 'constraint' => '^0.27'],
                'cviebrock/eloquent-sluggable' => ['type' => 'require', 'constraint' => '^7.0'],
                'cviebrock/eloquent-taggable' => ['type' => 'require', 'constraint' => '^7.0'],
                'dyrynda/laravel-ldap' => ['type' => 'require', 'constraint' => '^4.0'],
                'dyrynda/laravel-model-uuid' => ['type' => 'require', 'constraint' => '^6.0'],
                'elhebert/laravel-sri' => ['type' => 'require', 'constraint' => '^2.1'],
                'graham-campbell/markdown' => ['type' => 'require', 'constraint' => '^12.0'],
                'honeybadger-io/honeybadger-laravel' => ['type' => 'require', 'constraint' => '^3.0'],
                'iatstuti/laravel-cascade-soft-deletes' => ['type' => 'require', 'constraint' => '^3.0'],
                'jasonmccreary/laravel-test-assertions' => ['type' => 'require-dev', 'constraint' => '^0.5'],
                'laravel-frontend-presets/tailwindcss' => ['type' => 'require-dev', 'constraint' => '^4.0'],
                'laravel-relationship-events' => ['type' => 'require', 'constraint' => '^1.2'],
                'laravel-shift/blueprint' => ['type' => 'require-dev', 'constraint' => '^1.4'],
                'laravel-shift/console' => ['type' => 'require-dev', 'constraint' => '^0.2'],
                'laravel/browser-kit-testing' => ['type' => 'require-dev', 'constraint' => '^6.0'],
                'laravel/dusk' => ['type' => 'require-dev', 'constraint' => '^5.9'],
                'laravel/envoy' => ['type' => 'require', 'constraint' => '^2.0'],
                'laravel/horizon' => ['type' => 'require', 'constraint' => '^4.0'],
                'laravel/nova' => ['type' => 'require', 'constraint' => '^3.0'],
                'laravel/passport' => ['type' => 'require', 'constraint' => '^8.4'],
                'laravel/scout' => ['type' => 'require', 'constraint' => '^8.0'],
                'laravel/socialite' => ['type' => 'require', 'constraint' => '^4.3'],
                'laravel/telescope' => ['type' => 'require-dev', 'constraint' => '^3.1'],
                'laravelcollective/html' => ['type' => 'require', 'constraint' => '^6.1'],
                'maatwebsite/excel' => ['type' => 'require', 'constraint' => '^3.1.19'],
                'milon/barcode' => ['type' => 'require', 'constraint' => '^7.0'],
                'mpociot/laravel-test-factory-helper' => ['type' => 'require-dev', 'constraint' => '^2.1'],
                'mpociot/teamwork' => ['type' => 'require', 'constraint' => '^6.0'],
                'naoray/laravel-factory-prefill' => ['type' => 'require-dev', 'constraint' => '^2.0'],
                'nunomaduro/larastan' => ['type' => 'require-dev', 'constraint' => '^0.5'],
                'orchestral/testbench' => ['type' => 'require-dev', 'constraint' => '^5.0'],
                'rollbar/rollbar-laravel' => ['type' => 'require', 'constraint' => '^6.0'],
                'santigarcor/laratrust' => ['type' => 'require', 'constraint' => '^6.1'],
                'sentry/sentry-laravel' => ['type' => 'require', 'constraint' => '^1.7'],
                'spatie/eloquent-sortable' => ['type' => 'require', 'constraint' => '^3.8'],
                'spatie/laravel-activitylog' => ['type' => 'require', 'constraint' => '^3.11'],
                'spatie/laravel-analytics' => ['type' => 'require', 'constraint' => '^3.9'],
                'spatie/laravel-artisan-dd' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-backup' => ['type' => 'require', 'constraint' => '^6.8'],
                'spatie/laravel-blade-javascript' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-blink' => ['type' => 'require', 'constraint' => '^1.4'],
                'spatie/laravel-collection-macros' => ['type' => 'require', 'constraint' => '^6.1'],
                'spatie/laravel-cookie-consent' => ['type' => 'require', 'constraint' => '^2.12'],
                'spatie/laravel-csp' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-database-mail-templates' => ['type' => 'require', 'constraint' => '^3.3'],
                'spatie/laravel-db-snapshots' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-demo-mode' => ['type' => 'require', 'constraint' => '^2.6'],
                'spatie/laravel-event-projector' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/laravel-event-sourcing' => ['type' => 'require', 'constraint' => '^3.1'],
                'spatie/laravel-failed-job-monitor' => ['type' => 'require', 'constraint' => '^3.3'],
                'spatie/laravel-feed' => ['type' => 'require', 'constraint' => '^2.6'],
                'spatie/laravel-flash' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-fractal' => ['type' => 'require', 'constraint' => '^5.7'],
                'spatie/laravel-glide' => ['type' => 'require', 'constraint' => '^3.5'],
                'spatie/laravel-google-calendar' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-honeypot' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-html' => ['type' => 'require', 'constraint' => '^2.25'],
                'spatie/laravel-http-logger' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-image-optimizer' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-json-api-paginate' => ['type' => 'require', 'constraint' => '^1.7'],
                'spatie/laravel-mailable-test' => ['type' => 'require', 'constraint' => '^2.2'],
                'spatie/laravel-medialibrary' => ['type' => 'require', 'constraint' => '^7.19'],
                'spatie/laravel-menu' => ['type' => 'require', 'constraint' => '^3.5'],
                'spatie/laravel-missing-page-redirector' => ['type' => 'require', 'constraint' => '^2.6'],
                'spatie/laravel-model-cleanup' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-model-states' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-model-status' => ['type' => 'require', 'constraint' => '^1.10'],
                'spatie/laravel-newsletter' => ['type' => 'require', 'constraint' => '^4.8'],
                'spatie/laravel-permission' => ['type' => 'require', 'constraint' => '^3.6'],
                'spatie/laravel-personal-data-export' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-query-builder' => ['type' => 'require', 'constraint' => '^2.8'],
                'spatie/laravel-queueable-action' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-rate-limited-job-middleware' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-referer' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-responsecache' => ['type' => 'require', 'constraint' => '^6.5'],
                'spatie/laravel-robots-middleware' => ['type' => 'require', 'constraint' => '^1.2'],
                'spatie/laravel-schemaless-attributes' => ['type' => 'require', 'constraint' => '^1.7'],
                'spatie/laravel-searchable' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-server-monitor' => ['type' => 'require', 'constraint' => '^1.9'],
                'spatie/laravel-sitemap' => ['type' => 'require', 'constraint' => '^5.7'],
                'spatie/laravel-sluggable' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-stripe-webhooks' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-tags' => ['type' => 'require', 'constraint' => '^2.6'],
                'spatie/laravel-tail' => ['type' => 'require', 'constraint' => '^4.2'],
                'spatie/laravel-translatable' => ['type' => 'require', 'constraint' => '^4.3'],
                'spatie/laravel-translation-loader' => ['type' => 'require', 'constraint' => '^2.6'],
                'spatie/laravel-twitter-streaming-api' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-validation-rules' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-varnish' => ['type' => 'require', 'constraint' => '^2.7'],
                'spatie/laravel-view-components' => ['type' => 'require', 'constraint' => '^1.7'],
                'spatie/laravel-view-models' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-web-tinker' => ['type' => 'require', 'constraint' => '^1.7'],
                'spatie/laravel-webhook-client' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-webhook-server' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/nova-backup-tool' => ['type' => 'require', 'constraint' => '^4.0'],
                'spatie/nova-tags-field' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/nova-tail-tool' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/nova-translatable' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/sheets' => ['type' => 'require', 'constraint' => '^1.4'],
                'teamtnt/laravel-scout-tntsearch-driver' => ['type' => 'require', 'constraint' => '^8.0'],
                'therobfonz/laravel-mandrill-driver' => ['type' => 'require', 'constraint' => '^2.0'],
                'tightenco/ziggy' => ['type' => 'require', 'constraint' => '^0.8'],
                'torann/geoip' => ['type' => 'require', 'constraint' => '^1.2'],
                'vinkla/hashids' => ['type' => 'require', 'constraint' => '^8.0'],
                'watson/rememberable' => ['type' => 'require', 'constraint' => '^4.0'],
                'wnx/laravel-stats' => ['type' => 'require-dev', 'constraint' => '^2.0'],
            ],
            '6.0' => [
                'arcanedev/log-viewer' => ['type' => 'require', 'constraint' => '^5.0'],
                'barryvdh/laravel-cors' => ['type' => 'require', 'constraint' => '^0.11.4'],
                'barryvdh/laravel-dompdf' => ['type' => 'require', 'constraint' => '^0.8.5'],
                'barryvdh/laravel-ide-helper' => ['type' => 'require-dev', 'constraint' => '^2.6'],
                'beyondcode/laravel-websockets' => ['type' => 'require', 'constraint' => '^1.3'],
                'codedungeon/phpunit-result-printer' => ['type' => 'require-dev', 'constraint' => '^0.26'],
                'cviebrock/eloquent-sluggable' => ['type' => 'require', 'constraint' => '^6.0.0'],
                'cviebrock/eloquent-taggable' => ['type' => 'require', 'constraint' => '^6.0'],
                'dyrynda/laravel-model-uuid' => ['type' => 'require', 'constraint' => '^4.0'],
                'elhebert/laravel-sri' => ['type' => 'require', 'constraint' => '^2.0'],
                'famdirksen/laravel-job-handler' => ['type' => 'require', 'constraint' => '^0.2'],
                'graham-campbell/markdown' => ['type' => 'require', 'constraint' => '^11.2'],
                'iatstuti/laravel-cascade-soft-deletes' => ['type' => 'require', 'constraint' => '^2.0'],
                'jasonmccreary/laravel-test-assertions' => ['type' => 'require-dev', 'constraint' => '^0.3'],
                'jhoff/blade-vue-directive' => ['type' => 'require', 'constraint' => '^2.1'],
                'kalnoy/nestedset' => ['type' => 'require', 'constraint' => '^5.0'],
                'laravel-frontend-presets/tailwindcss' => ['type' => 'require-dev', 'constraint' => '^2.0'],
                'laravel/browser-kit-testing' => ['type' => 'require-dev', 'constraint' => '^5.1.3'],
                'laravel/dusk' => ['type' => 'require-dev', 'constraint' => '^5.8'],
                'laravel/horizon' => ['type' => 'require', 'constraint' => '^3.2.7'],
                'laravel/nova' => ['type' => 'require', 'constraint' => '^2.3'],
                'laravel/passport' => ['type' => 'require', 'constraint' => '^7.5'],
                'laravel/scout' => ['type' => 'require', 'constraint' => '^7.2'],
                'laravel/socialite' => ['type' => 'require', 'constraint' => '^4.2'],
                'laravel/telescope' => ['type' => 'require-dev', 'constraint' => '^2.1'],
                'laravelcollective/html' => ['type' => 'require', 'constraint' => '^6.0'],
                'laravelium/sitemap' => ['type' => 'require', 'constraint' => '^6.0'],
                'maatwebsite/excel' => ['type' => 'require', 'constraint' => '^3.1.16'],
                'milon/barcode' => ['type' => 'require', 'constraint' => '^6.0'],
                'mpociot/laravel-test-factory-helper' => ['type' => 'require-dev', 'constraint' => '^2.0'],
                'mpociot/teamwork' => ['type' => 'require', 'constraint' => '^5.3'],
                'naoray/laravel-factory-prefill' => ['type' => 'require-dev', 'constraint' => '^1.3'],
                'nunomaduro/larastan' => ['type' => 'require-dev', 'constraint' => '^0.4.0'],
                'orchestral/testbench' => ['type' => 'require-dev', 'constraint' => '^4.0'],
                'rollbar/rollbar-laravel' => ['type' => 'require', 'constraint' => '^5.0'],
                'santigarcor/laratrust' => ['type' => 'require', 'constraint' => '^5.2.3'],
                'sentry/sentry-laravel' => ['type' => 'require', 'constraint' => '^1.6'],
                'smodav/mpesa' => ['type' => 'require', 'constraint' => '^4.1'],
                'spatie/eloquent-sortable' => ['type' => 'require', 'constraint' => '^3.7'],
                'spatie/laravel-activitylog' => ['type' => 'require', 'constraint' => '^3.8'],
                'spatie/laravel-analytics' => ['type' => 'require', 'constraint' => '^3.8'],
                'spatie/laravel-artisan-dd' => ['type' => 'require', 'constraint' => '^2.2'],
                'spatie/laravel-backup' => ['type' => 'require', 'constraint' => '^6.4'],
                'spatie/laravel-blade-javascript' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-blade-x' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-blink' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-collection-macros' => ['type' => 'require', 'constraint' => '^6.0'],
                'spatie/laravel-cookie-consent' => ['type' => 'require', 'constraint' => '^2.9'],
                'spatie/laravel-cors' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-csp' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-database-mail-templates' => ['type' => 'require', 'constraint' => '^3.2'],
                'spatie/laravel-demo-mode' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-event-projector' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/laravel-failed-job-monitor' => ['type' => 'require', 'constraint' => '^3.2'],
                'spatie/laravel-feed' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-fractal' => ['type' => 'require', 'constraint' => '^5.6'],
                'spatie/laravel-glide' => ['type' => 'require', 'constraint' => '^3.4'],
                'spatie/laravel-google-calendar' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-honeypot' => ['type' => 'require', 'constraint' => '^1.4'],
                'spatie/laravel-html' => ['type' => 'require', 'constraint' => '^2.23'],
                'spatie/laravel-http-logger' => ['type' => 'require', 'constraint' => '^1.3'],
                'spatie/laravel-image-optimizer' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-json-api-paginate' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-mailable-test' => ['type' => 'require', 'constraint' => '^2.1'],
                'spatie/laravel-medialibrary' => ['type' => 'require', 'constraint' => '^7.12'],
                'spatie/laravel-menu' => ['type' => 'require', 'constraint' => '^3.4'],
                'spatie/laravel-missing-page-redirector' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-model-cleanup' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-model-status' => ['type' => 'require', 'constraint' => '^1.8'],
                'spatie/laravel-newsletter' => ['type' => 'require', 'constraint' => '^4.6'],
                'spatie/laravel-permission' => ['type' => 'require', 'constraint' => '^3.0'],
                'spatie/laravel-query-builder' => ['type' => 'require', 'constraint' => '^2.1'],
                'spatie/laravel-queueable-action' => ['type' => 'require', 'constraint' => '^2.2'],
                'spatie/laravel-referer' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-responsecache' => ['type' => 'require', 'constraint' => '^6.2'],
                'spatie/laravel-schemaless-attributes' => ['type' => 'require', 'constraint' => '^1.6'],
                'spatie/laravel-searchable' => ['type' => 'require', 'constraint' => '^1.4'],
                'spatie/laravel-server-monitor' => ['type' => 'require', 'constraint' => '^1.8'],
                'spatie/laravel-sitemap' => ['type' => 'require', 'constraint' => '^5.4'],
                'spatie/laravel-sluggable' => ['type' => 'require', 'constraint' => '^2.2'],
                'spatie/laravel-stripe-webhooks' => ['type' => 'require', 'constraint' => '^2.2.1'],
                'spatie/laravel-tags' => ['type' => 'require', 'constraint' => '^2.5'],
                'spatie/laravel-tail' => ['type' => 'require', 'constraint' => '^3.3'],
                'spatie/laravel-translatable' => ['type' => 'require', 'constraint' => '^4.2'],
                'spatie/laravel-translation-loader' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-twitter-streaming-api' => ['type' => 'require', 'constraint' => '^1.2'],
                'spatie/laravel-validation-rules' => ['type' => 'require', 'constraint' => '^2.4'],
                'spatie/laravel-varnish' => ['type' => 'require', 'constraint' => '^2.3'],
                'spatie/laravel-view-components' => ['type' => 'require', 'constraint' => '^1.2'],
                'spatie/laravel-view-models' => ['type' => 'require', 'constraint' => '^1.2'],
                'spatie/laravel-web-tinker' => ['type' => 'require', 'constraint' => '^1.5'],
                'spatie/laravel-webhook-client' => ['type' => 'require', 'constraint' => '^2.2'],
                'spatie/laravel-webhook-server' => ['type' => 'require', 'constraint' => '^1.1'],
                'spatie/nova-backup-tool' => ['type' => 'require', 'constraint' => '^3.2'],
                'spatie/nova-tail-tool' => ['type' => 'require', 'constraint' => '^2.1'],
                'spatie/sheets' => ['type' => 'require', 'constraint' => '^1.3'],
                'teamtnt/laravel-scout-tntsearch-driver' => ['type' => 'require', 'constraint' => '^7.2'],
                'tightenco/ziggy' => ['type' => 'require', 'constraint' => '^0.8.0'],
                'two-thirds/eloquent-traits' => ['type' => 'require', 'constraint' => '^1.5'],
                'two-thirds/laravel-test-suite' => ['type' => 'require-dev', 'constraint' => '^4.1'],
                'vinkla/hashids' => ['type' => 'require', 'constraint' => '^7.0'],
                'watson/rememberable' => ['type' => 'require', 'constraint' => '^3.1'],
                'wnx/laravel-stats' => ['type' => 'require-dev', 'constraint' => '^2.0'],
            ],
        ];

        return $constraints[$version] ?? [];
    }

    public static function illuminatePackages()
    {
        return [
            'illuminate/auth',
            'illuminate/broadcasting',
            'illuminate/bus',
            'illuminate/cache',
            'illuminate/config',
            'illuminate/console',
            'illuminate/container',
            'illuminate/contracts',
            'illuminate/cookie',
            'illuminate/database',
            'illuminate/encryption',
            'illuminate/events',
            'illuminate/filesystem',
            'illuminate/hashing',
            'illuminate/http',
            'illuminate/log',
            'illuminate/mail',
            'illuminate/notifications',
            'illuminate/pagination',
            'illuminate/pipeline',
            'illuminate/queue',
            'illuminate/redis',
            'illuminate/routing',
            'illuminate/session',
            'illuminate/support',
            'illuminate/testing',
            'illuminate/translation',
            'illuminate/validation',
            'illuminate/view',
        ];
    }
}
